# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5b6ba48a4966d16a0a90d4fcdbc44899241e13f048208104e644d5f44b80e3df35a4b9192cb7ebe31c9cacf36e5ac17e16e0b18ca477b0e043dd725b413b62

test:
  secret_key_base: 15b7021374162243490338df917c6f4eefcce2c05ebd75bcde4ba249f6a2a5b727c5109dd9604978565eed1ebcb6fc29c0e4261bd80b599b9d1691e0997fde8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
